### ISSUE TITLE
Hero section responsive, problem

### ISSUE THREAD

**Issue by brokenfingers** [front-end-by-rimantas/32-grupe-portfolio-braintech#38]
.hero img - selector is going outside the windows when resizing. i missed that when i was doing review.

**Comment by nsn1930** [comment]
Same as in original site. Tried to copy that.

**Comment by brokenfingers** [comment]
not full responsive done. horizontal scrollbars appears when resizing, on original not.

**Comment by brokenfingers** [comment]
posible solution(if its not forbidden):
  it would keep image out of the screen without appearance of horizontal scrollbar.
.container.hero{
  overflow: hidden;
}
